Repository demaceo/fitlit, pull requests merged in 2020-10, with the labels that each got.

#42 Iteration1/classes and methods
  src/User.js
  src/UserRepository.js
  src/activityRepository.js
  src/hydrationRepository.js
  src/sleepRepository.js
  test/ActivityRepository-test.js
  test/HydrationRepository-test.js
  test/SleepRepository-test.js
Labels: TDD testing, feature

#43 Organizing UserRepository to distribute all fetched data
  src/User.js
  src/UserRepository.js
  src/scripts.js
Labels: feature

#44 Fetching and Instantiating User through data model
  dist/index.html
  package-lock.json
  package.json
  src/User.js
  src/UserRepository.js
  src/activityRepository.js
  src/domupdates.js
  src/fetch.js
  src/scripts.js
  src/sleepRepository.js
  test/UserRepository-test.js
Labels: Async, feature

#46 Iteration2/hydration tdd
  dist/index.html
  package-lock.json
  package.json
  src/User.js
  src/UserRepository.js
  src/activityRepository.js
  src/domupdates.js
  src/fetch.js
  src/hydrationRepository.js
  src/scripts.js
  src/sleepRepository.js
  test/HydrationRepository-test.js
  test/UserRepository-test.js
Labels: TDD testing, enhancement

#45 basic setup for tests created
  src/activityRepository.js
  test/ActivityRepository-test.js
Labels: TDD testing

#47 Realignment of Files for Version Control
  src/activityRepository.js
  src/hydrationRepository.js
  test/HydrationRepository-test.js
Labels: bug, duplicate

#48 Features/instantiating user
  src/domUpdates.js
  src/fetch.js
  src/scripts.js
Labels: bug, duplicate

#52 Realign Files 2
  src/scripts.js
Labels: bug
