Repository demaceo/fitlit, pull requests merged in 2020-11, with the labels that each got.

#55 Hydration Repository and Test Files
  src/User.js
  src/UserRepository.js
  src/hydrationRepository.js
  test/ActivityRepository-test.js
  test/HydrationRepository-test.js
  test/UserRepository-test.js
Labels: feature

#56 completed activity repo tests and methods
  src/activityRepository.js
  test/ActivityRepository-test.js
Labels: TDD testing

#57 Feature/activity repo
  src/UserRepository.js
  src/activityRepository.js
  src/css/_buttons.scss
  src/css/_headers.scss
  src/css/_text-elements.scss
  src/css/styles.scss
  src/domUpdates.js
  src/index.html
  src/scripts.js
Labels: Accessibility, feature

#58 Sleep tdd
  src/sleepRepository.js
  test/HydrationRepository-test.js
  test/SleepRepository-test.js
Labels: enhancement

#59 Final Modifications to Scripts and DomUpdater
  src/User.js
  src/domUpdates.js
  src/index.html
  src/scripts.js
Labels: Async, bug
